title: "Blog del Equipo EscuderoGarcia"
email: vuestros-correos@ual.es
description: >-
  Espacio colaborativo del equipo EscuderoGarcia para la asignatura 
  Herramientas y Métodos en Ingeniería del Software (HMIS 2026).
theme: minima

# Plugins para mejorar el rendimiento y el SEO
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluimos archivos basura para que compile más rápido
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
